volumes:
  postgres_data_cw:

services:
  postgres:
    image: postgres:latest
    container_name: postgres_cw
    environment:
      POSTGRES_USER: cw
      POSTGRES_PASSWORD: cw
      POSTGRES_DB: cw
    ports:
      - '5435:5432'
    volumes:
      - postgres_data_cw:/var/lib/postgresql/data